// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: cafe.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProductType int32

const (
	ProductType_PRODUCT_TYPE_UNKNOWN  ProductType = 0
	ProductType_PRODUCT_TYPE_FOOD     ProductType = 1
	ProductType_PRODUCT_TYPE_BEVERAGE ProductType = 2
)

// Enum value maps for ProductType.
var (
	ProductType_name = map[int32]string{
		0: "PRODUCT_TYPE_UNKNOWN",
		1: "PRODUCT_TYPE_FOOD",
		2: "PRODUCT_TYPE_BEVERAGE",
	}
	ProductType_value = map[string]int32{
		"PRODUCT_TYPE_UNKNOWN":  0,
		"PRODUCT_TYPE_FOOD":     1,
		"PRODUCT_TYPE_BEVERAGE": 2,
	}
)

func (x ProductType) Enum() *ProductType {
	p := new(ProductType)
	*p = x
	return p
}

func (x ProductType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProductType) Descriptor() protoreflect.EnumDescriptor {
	return file_cafe_proto_enumTypes[0].Descriptor()
}

func (ProductType) Type() protoreflect.EnumType {
	return &file_cafe_proto_enumTypes[0]
}

func (x ProductType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProductType.Descriptor instead.
func (ProductType) EnumDescriptor() ([]byte, []int) {
	return file_cafe_proto_rawDescGZIP(), []int{0}
}

type KitchenOrderItemStatus int32

const (
	KitchenOrderItemStatus_KITCHEN_ORDER_ITEM_STATUS_PENDING   KitchenOrderItemStatus = 0
	KitchenOrderItemStatus_KITCHEN_ORDER_ITEM_STATUS_STARTED   KitchenOrderItemStatus = 1
	KitchenOrderItemStatus_KITCHEN_ORDER_ITEM_STATUS_COMPLETED KitchenOrderItemStatus = 2
	KitchenOrderItemStatus_KITCHEN_ORDER_ITEM_STATUS_FAILED    KitchenOrderItemStatus = 3
)

// Enum value maps for KitchenOrderItemStatus.
var (
	KitchenOrderItemStatus_name = map[int32]string{
		0: "KITCHEN_ORDER_ITEM_STATUS_PENDING",
		1: "KITCHEN_ORDER_ITEM_STATUS_STARTED",
		2: "KITCHEN_ORDER_ITEM_STATUS_COMPLETED",
		3: "KITCHEN_ORDER_ITEM_STATUS_FAILED",
	}
	KitchenOrderItemStatus_value = map[string]int32{
		"KITCHEN_ORDER_ITEM_STATUS_PENDING":   0,
		"KITCHEN_ORDER_ITEM_STATUS_STARTED":   1,
		"KITCHEN_ORDER_ITEM_STATUS_COMPLETED": 2,
		"KITCHEN_ORDER_ITEM_STATUS_FAILED":    3,
	}
)

func (x KitchenOrderItemStatus) Enum() *KitchenOrderItemStatus {
	p := new(KitchenOrderItemStatus)
	*p = x
	return p
}

func (x KitchenOrderItemStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (KitchenOrderItemStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_cafe_proto_enumTypes[1].Descriptor()
}

func (KitchenOrderItemStatus) Type() protoreflect.EnumType {
	return &file_cafe_proto_enumTypes[1]
}

func (x KitchenOrderItemStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use KitchenOrderItemStatus.Descriptor instead.
func (KitchenOrderItemStatus) EnumDescriptor() ([]byte, []int) {
	return file_cafe_proto_rawDescGZIP(), []int{1}
}

type BaristaOrderItemStatus int32

const (
	BaristaOrderItemStatus_BARISTA_ORDER_ITEM_STATUS_PENDING   BaristaOrderItemStatus = 0
	BaristaOrderItemStatus_BARISTA_ORDER_ITEM_STATUS_STARTED   BaristaOrderItemStatus = 1
	BaristaOrderItemStatus_BARISTA_ORDER_ITEM_STATUS_COMPLETED BaristaOrderItemStatus = 2
	BaristaOrderItemStatus_BARISTA_ORDER_ITEM_STATUS_FAILED    BaristaOrderItemStatus = 3
)

// Enum value maps for BaristaOrderItemStatus.
var (
	BaristaOrderItemStatus_name = map[int32]string{
		0: "BARISTA_ORDER_ITEM_STATUS_PENDING",
		1: "BARISTA_ORDER_ITEM_STATUS_STARTED",
		2: "BARISTA_ORDER_ITEM_STATUS_COMPLETED",
		3: "BARISTA_ORDER_ITEM_STATUS_FAILED",
	}
	BaristaOrderItemStatus_value = map[string]int32{
		"BARISTA_ORDER_ITEM_STATUS_PENDING":   0,
		"BARISTA_ORDER_ITEM_STATUS_STARTED":   1,
		"BARISTA_ORDER_ITEM_STATUS_COMPLETED": 2,
		"BARISTA_ORDER_ITEM_STATUS_FAILED":    3,
	}
)

func (x BaristaOrderItemStatus) Enum() *BaristaOrderItemStatus {
	p := new(BaristaOrderItemStatus)
	*p = x
	return p
}

func (x BaristaOrderItemStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BaristaOrderItemStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_cafe_proto_enumTypes[2].Descriptor()
}

func (BaristaOrderItemStatus) Type() protoreflect.EnumType {
	return &file_cafe_proto_enumTypes[2]
}

func (x BaristaOrderItemStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BaristaOrderItemStatus.Descriptor instead.
func (BaristaOrderItemStatus) EnumDescriptor() ([]byte, []int) {
	return file_cafe_proto_rawDescGZIP(), []int{2}
}

type OrderLineItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type  ProductType `protobuf:"varint,1,opt,name=type,proto3,enum=temporalio.cafe.ProductType" json:"type,omitempty"`
	Name  string      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Price uint32      `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Count uint32      `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *OrderLineItem) Reset() {
	*x = OrderLineItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cafe_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderLineItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderLineItem) ProtoMessage() {}

func (x *OrderLineItem) ProtoReflect() protoreflect.Message {
	mi := &file_cafe_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderLineItem.ProtoReflect.Descriptor instead.
func (*OrderLineItem) Descriptor() ([]byte, []int) {
	return file_cafe_proto_rawDescGZIP(), []int{0}
}

func (x *OrderLineItem) GetType() ProductType {
	if x != nil {
		return x.Type
	}
	return ProductType_PRODUCT_TYPE_UNKNOWN
}

func (x *OrderLineItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrderLineItem) GetPrice() uint32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderLineItem) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type OrderInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email        string           `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	PaymentToken string           `protobuf:"bytes,2,opt,name=payment_token,json=paymentToken,proto3" json:"payment_token,omitempty"`
	Items        []*OrderLineItem `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *OrderInput) Reset() {
	*x = OrderInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cafe_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderInput) ProtoMessage() {}

func (x *OrderInput) ProtoReflect() protoreflect.Message {
	mi := &file_cafe_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderInput.ProtoReflect.Descriptor instead.
func (*OrderInput) Descriptor() ([]byte, []int) {
	return file_cafe_proto_rawDescGZIP(), []int{1}
}

func (x *OrderInput) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *OrderInput) GetPaymentToken() string {
	if x != nil {
		return x.PaymentToken
	}
	return ""
}

func (x *OrderInput) GetItems() []*OrderLineItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type OrderResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OrderResult) Reset() {
	*x = OrderResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cafe_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderResult) ProtoMessage() {}

func (x *OrderResult) ProtoReflect() protoreflect.Message {
	mi := &file_cafe_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderResult.ProtoReflect.Descriptor instead.
func (*OrderResult) Descriptor() ([]byte, []int) {
	return file_cafe_proto_rawDescGZIP(), []int{2}
}

type KitchenOrderLineItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status KitchenOrderItemStatus `protobuf:"varint,2,opt,name=status,proto3,enum=temporalio.cafe.KitchenOrderItemStatus" json:"status,omitempty"`
}

func (x *KitchenOrderLineItem) Reset() {
	*x = KitchenOrderLineItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cafe_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KitchenOrderLineItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KitchenOrderLineItem) ProtoMessage() {}

func (x *KitchenOrderLineItem) ProtoReflect() protoreflect.Message {
	mi := &file_cafe_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KitchenOrderLineItem.ProtoReflect.Descriptor instead.
func (*KitchenOrderLineItem) Descriptor() ([]byte, []int) {
	return file_cafe_proto_rawDescGZIP(), []int{3}
}

func (x *KitchenOrderLineItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *KitchenOrderLineItem) GetStatus() KitchenOrderItemStatus {
	if x != nil {
		return x.Status
	}
	return KitchenOrderItemStatus_KITCHEN_ORDER_ITEM_STATUS_PENDING
}

type KitchenOrderInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*OrderLineItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *KitchenOrderInput) Reset() {
	*x = KitchenOrderInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cafe_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KitchenOrderInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KitchenOrderInput) ProtoMessage() {}

func (x *KitchenOrderInput) ProtoReflect() protoreflect.Message {
	mi := &file_cafe_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KitchenOrderInput.ProtoReflect.Descriptor instead.
func (*KitchenOrderInput) Descriptor() ([]byte, []int) {
	return file_cafe_proto_rawDescGZIP(), []int{4}
}

func (x *KitchenOrderInput) GetItems() []*OrderLineItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type KitchenOrderItemStatusUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Line   uint32                 `protobuf:"varint,1,opt,name=line,proto3" json:"line,omitempty"`
	Status KitchenOrderItemStatus `protobuf:"varint,2,opt,name=status,proto3,enum=temporalio.cafe.KitchenOrderItemStatus" json:"status,omitempty"`
}

func (x *KitchenOrderItemStatusUpdate) Reset() {
	*x = KitchenOrderItemStatusUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cafe_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KitchenOrderItemStatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KitchenOrderItemStatusUpdate) ProtoMessage() {}

func (x *KitchenOrderItemStatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_cafe_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KitchenOrderItemStatusUpdate.ProtoReflect.Descriptor instead.
func (*KitchenOrderItemStatusUpdate) Descriptor() ([]byte, []int) {
	return file_cafe_proto_rawDescGZIP(), []int{5}
}

func (x *KitchenOrderItemStatusUpdate) GetLine() uint32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *KitchenOrderItemStatusUpdate) GetStatus() KitchenOrderItemStatus {
	if x != nil {
		return x.Status
	}
	return KitchenOrderItemStatus_KITCHEN_ORDER_ITEM_STATUS_PENDING
}

type KitchenOrderStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Open  bool                    `protobuf:"varint,1,opt,name=open,proto3" json:"open,omitempty"`
	Items []*KitchenOrderLineItem `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *KitchenOrderStatus) Reset() {
	*x = KitchenOrderStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cafe_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KitchenOrderStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KitchenOrderStatus) ProtoMessage() {}

func (x *KitchenOrderStatus) ProtoReflect() protoreflect.Message {
	mi := &file_cafe_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KitchenOrderStatus.ProtoReflect.Descriptor instead.
func (*KitchenOrderStatus) Descriptor() ([]byte, []int) {
	return file_cafe_proto_rawDescGZIP(), []int{6}
}

func (x *KitchenOrderStatus) GetOpen() bool {
	if x != nil {
		return x.Open
	}
	return false
}

func (x *KitchenOrderStatus) GetItems() []*KitchenOrderLineItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type KitchenOrderResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *KitchenOrderResult) Reset() {
	*x = KitchenOrderResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cafe_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KitchenOrderResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KitchenOrderResult) ProtoMessage() {}

func (x *KitchenOrderResult) ProtoReflect() protoreflect.Message {
	mi := &file_cafe_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KitchenOrderResult.ProtoReflect.Descriptor instead.
func (*KitchenOrderResult) Descriptor() ([]byte, []int) {
	return file_cafe_proto_rawDescGZIP(), []int{7}
}

type BaristaOrderLineItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status BaristaOrderItemStatus `protobuf:"varint,2,opt,name=status,proto3,enum=temporalio.cafe.BaristaOrderItemStatus" json:"status,omitempty"`
}

func (x *BaristaOrderLineItem) Reset() {
	*x = BaristaOrderLineItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cafe_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BaristaOrderLineItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaristaOrderLineItem) ProtoMessage() {}

func (x *BaristaOrderLineItem) ProtoReflect() protoreflect.Message {
	mi := &file_cafe_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaristaOrderLineItem.ProtoReflect.Descriptor instead.
func (*BaristaOrderLineItem) Descriptor() ([]byte, []int) {
	return file_cafe_proto_rawDescGZIP(), []int{8}
}

func (x *BaristaOrderLineItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BaristaOrderLineItem) GetStatus() BaristaOrderItemStatus {
	if x != nil {
		return x.Status
	}
	return BaristaOrderItemStatus_BARISTA_ORDER_ITEM_STATUS_PENDING
}

type BaristaOrderInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*OrderLineItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *BaristaOrderInput) Reset() {
	*x = BaristaOrderInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cafe_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BaristaOrderInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaristaOrderInput) ProtoMessage() {}

func (x *BaristaOrderInput) ProtoReflect() protoreflect.Message {
	mi := &file_cafe_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaristaOrderInput.ProtoReflect.Descriptor instead.
func (*BaristaOrderInput) Descriptor() ([]byte, []int) {
	return file_cafe_proto_rawDescGZIP(), []int{9}
}

func (x *BaristaOrderInput) GetItems() []*OrderLineItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type BaristaOrderItemStatusUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Line   uint32                 `protobuf:"varint,1,opt,name=line,proto3" json:"line,omitempty"`
	Status BaristaOrderItemStatus `protobuf:"varint,2,opt,name=status,proto3,enum=temporalio.cafe.BaristaOrderItemStatus" json:"status,omitempty"`
}

func (x *BaristaOrderItemStatusUpdate) Reset() {
	*x = BaristaOrderItemStatusUpdate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cafe_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BaristaOrderItemStatusUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaristaOrderItemStatusUpdate) ProtoMessage() {}

func (x *BaristaOrderItemStatusUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_cafe_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaristaOrderItemStatusUpdate.ProtoReflect.Descriptor instead.
func (*BaristaOrderItemStatusUpdate) Descriptor() ([]byte, []int) {
	return file_cafe_proto_rawDescGZIP(), []int{10}
}

func (x *BaristaOrderItemStatusUpdate) GetLine() uint32 {
	if x != nil {
		return x.Line
	}
	return 0
}

func (x *BaristaOrderItemStatusUpdate) GetStatus() BaristaOrderItemStatus {
	if x != nil {
		return x.Status
	}
	return BaristaOrderItemStatus_BARISTA_ORDER_ITEM_STATUS_PENDING
}

type BaristaOrderStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Open  bool                    `protobuf:"varint,1,opt,name=open,proto3" json:"open,omitempty"`
	Items []*BaristaOrderLineItem `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *BaristaOrderStatus) Reset() {
	*x = BaristaOrderStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cafe_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BaristaOrderStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaristaOrderStatus) ProtoMessage() {}

func (x *BaristaOrderStatus) ProtoReflect() protoreflect.Message {
	mi := &file_cafe_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaristaOrderStatus.ProtoReflect.Descriptor instead.
func (*BaristaOrderStatus) Descriptor() ([]byte, []int) {
	return file_cafe_proto_rawDescGZIP(), []int{11}
}

func (x *BaristaOrderStatus) GetOpen() bool {
	if x != nil {
		return x.Open
	}
	return false
}

func (x *BaristaOrderStatus) GetItems() []*BaristaOrderLineItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type BaristaOrderResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BaristaOrderResult) Reset() {
	*x = BaristaOrderResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cafe_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BaristaOrderResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaristaOrderResult) ProtoMessage() {}

func (x *BaristaOrderResult) ProtoReflect() protoreflect.Message {
	mi := &file_cafe_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaristaOrderResult.ProtoReflect.Descriptor instead.
func (*BaristaOrderResult) Descriptor() ([]byte, []int) {
	return file_cafe_proto_rawDescGZIP(), []int{12}
}

type CustomerLoyaltyPointsBalance struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Points uint32 `protobuf:"varint,1,opt,name=points,proto3" json:"points,omitempty"`
}

func (x *CustomerLoyaltyPointsBalance) Reset() {
	*x = CustomerLoyaltyPointsBalance{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cafe_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomerLoyaltyPointsBalance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerLoyaltyPointsBalance) ProtoMessage() {}

func (x *CustomerLoyaltyPointsBalance) ProtoReflect() protoreflect.Message {
	mi := &file_cafe_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerLoyaltyPointsBalance.ProtoReflect.Descriptor instead.
func (*CustomerLoyaltyPointsBalance) Descriptor() ([]byte, []int) {
	return file_cafe_proto_rawDescGZIP(), []int{13}
}

func (x *CustomerLoyaltyPointsBalance) GetPoints() uint32 {
	if x != nil {
		return x.Points
	}
	return 0
}

type CustomerLoyaltyPointsEarned struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Points uint32 `protobuf:"varint,1,opt,name=points,proto3" json:"points,omitempty"`
}

func (x *CustomerLoyaltyPointsEarned) Reset() {
	*x = CustomerLoyaltyPointsEarned{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cafe_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomerLoyaltyPointsEarned) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerLoyaltyPointsEarned) ProtoMessage() {}

func (x *CustomerLoyaltyPointsEarned) ProtoReflect() protoreflect.Message {
	mi := &file_cafe_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerLoyaltyPointsEarned.ProtoReflect.Descriptor instead.
func (*CustomerLoyaltyPointsEarned) Descriptor() ([]byte, []int) {
	return file_cafe_proto_rawDescGZIP(), []int{14}
}

func (x *CustomerLoyaltyPointsEarned) GetPoints() uint32 {
	if x != nil {
		return x.Points
	}
	return 0
}

type CustomerInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
}

func (x *CustomerInput) Reset() {
	*x = CustomerInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cafe_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CustomerInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CustomerInput) ProtoMessage() {}

func (x *CustomerInput) ProtoReflect() protoreflect.Message {
	mi := &file_cafe_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CustomerInput.ProtoReflect.Descriptor instead.
func (*CustomerInput) Descriptor() ([]byte, []int) {
	return file_cafe_proto_rawDescGZIP(), []int{15}
}

func (x *CustomerInput) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type Payment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Authcode string `protobuf:"bytes,1,opt,name=authcode,proto3" json:"authcode,omitempty"`
}

func (x *Payment) Reset() {
	*x = Payment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cafe_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Payment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Payment) ProtoMessage() {}

func (x *Payment) ProtoReflect() protoreflect.Message {
	mi := &file_cafe_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Payment.ProtoReflect.Descriptor instead.
func (*Payment) Descriptor() ([]byte, []int) {
	return file_cafe_proto_rawDescGZIP(), []int{16}
}

func (x *Payment) GetAuthcode() string {
	if x != nil {
		return x.Authcode
	}
	return ""
}

type ProcessPaymentInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
}

func (x *ProcessPaymentInput) Reset() {
	*x = ProcessPaymentInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cafe_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessPaymentInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPaymentInput) ProtoMessage() {}

func (x *ProcessPaymentInput) ProtoReflect() protoreflect.Message {
	mi := &file_cafe_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPaymentInput.ProtoReflect.Descriptor instead.
func (*ProcessPaymentInput) Descriptor() ([]byte, []int) {
	return file_cafe_proto_rawDescGZIP(), []int{17}
}

func (x *ProcessPaymentInput) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ProcessPaymentResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payment *Payment `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
}

func (x *ProcessPaymentResult) Reset() {
	*x = ProcessPaymentResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cafe_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessPaymentResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPaymentResult) ProtoMessage() {}

func (x *ProcessPaymentResult) ProtoReflect() protoreflect.Message {
	mi := &file_cafe_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPaymentResult.ProtoReflect.Descriptor instead.
func (*ProcessPaymentResult) Descriptor() ([]byte, []int) {
	return file_cafe_proto_rawDescGZIP(), []int{18}
}

func (x *ProcessPaymentResult) GetPayment() *Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

type ProcessPaymentRefundInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Payment *Payment `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
}

func (x *ProcessPaymentRefundInput) Reset() {
	*x = ProcessPaymentRefundInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cafe_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessPaymentRefundInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPaymentRefundInput) ProtoMessage() {}

func (x *ProcessPaymentRefundInput) ProtoReflect() protoreflect.Message {
	mi := &file_cafe_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPaymentRefundInput.ProtoReflect.Descriptor instead.
func (*ProcessPaymentRefundInput) Descriptor() ([]byte, []int) {
	return file_cafe_proto_rawDescGZIP(), []int{19}
}

func (x *ProcessPaymentRefundInput) GetPayment() *Payment {
	if x != nil {
		return x.Payment
	}
	return nil
}

type ProcessPaymentRefundResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ProcessPaymentRefundResult) Reset() {
	*x = ProcessPaymentRefundResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cafe_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcessPaymentRefundResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessPaymentRefundResult) ProtoMessage() {}

func (x *ProcessPaymentRefundResult) ProtoReflect() protoreflect.Message {
	mi := &file_cafe_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessPaymentRefundResult.ProtoReflect.Descriptor instead.
func (*ProcessPaymentRefundResult) Descriptor() ([]byte, []int) {
	return file_cafe_proto_rawDescGZIP(), []int{20}
}

type AddLoyaltyPointsInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email  string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Points uint32 `protobuf:"varint,2,opt,name=points,proto3" json:"points,omitempty"`
}

func (x *AddLoyaltyPointsInput) Reset() {
	*x = AddLoyaltyPointsInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cafe_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddLoyaltyPointsInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddLoyaltyPointsInput) ProtoMessage() {}

func (x *AddLoyaltyPointsInput) ProtoReflect() protoreflect.Message {
	mi := &file_cafe_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddLoyaltyPointsInput.ProtoReflect.Descriptor instead.
func (*AddLoyaltyPointsInput) Descriptor() ([]byte, []int) {
	return file_cafe_proto_rawDescGZIP(), []int{21}
}

func (x *AddLoyaltyPointsInput) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *AddLoyaltyPointsInput) GetPoints() uint32 {
	if x != nil {
		return x.Points
	}
	return 0
}

type AddLoyaltyPointsResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AddLoyaltyPointsResult) Reset() {
	*x = AddLoyaltyPointsResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_cafe_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddLoyaltyPointsResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddLoyaltyPointsResult) ProtoMessage() {}

func (x *AddLoyaltyPointsResult) ProtoReflect() protoreflect.Message {
	mi := &file_cafe_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddLoyaltyPointsResult.ProtoReflect.Descriptor instead.
func (*AddLoyaltyPointsResult) Descriptor() ([]byte, []int) {
	return file_cafe_proto_rawDescGZIP(), []int{22}
}

var File_cafe_proto protoreflect.FileDescriptor

var file_cafe_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x63, 0x61, 0x66, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x74, 0x65,
	0x6d, 0x70, 0x6f, 0x72, 0x61, 0x6c, 0x69, 0x6f, 0x2e, 0x63, 0x61, 0x66, 0x65, 0x1a, 0x1b, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65,
	0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x81, 0x01, 0x0a, 0x0d, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x4c, 0x69, 0x6e, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x30, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x74, 0x65, 0x6d,
	0x70, 0x6f, 0x72, 0x61, 0x6c, 0x69, 0x6f, 0x2e, 0x63, 0x61, 0x66, 0x65, 0x2e, 0x50, 0x72, 0x6f,
	0x64, 0x75, 0x63, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x7d,
	0x0a, 0x0a, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x61, 0x79, 0x6d, 0x65,
	0x6e, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x34, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x74, 0x65, 0x6d, 0x70, 0x6f, 0x72, 0x61,
	0x6c, 0x69, 0x6f, 0x2e, 0x63, 0x61, 0x66, 0x65, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4c, 0x69,
	0x6e, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x0d, 0x0a,
	0x0b, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x6b, 0x0a, 0x14,
	0x4b, 0x69, 0x74, 0x63, 0x68, 0x65, 0x6e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4c, 0x69, 0x6e, 0x65,
	0x49, 0x74, 0x65, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x3f, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x27, 0x2e, 0x74, 0x65, 0x6d, 0x70, 0x6f,
	0x72, 0x61, 0x6c, 0x69, 0x6f, 0x2e, 0x63, 0x61, 0x66, 0x65, 0x2e, 0x4b, 0x69, 0x74, 0x63, 0x68,
	0x65, 0x6e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x49, 0x0a, 0x11, 0x4b, 0x69, 0x74,
	0x63, 0x68, 0x65, 0x6e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x34,
	0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e,
	0x74, 0x65, 0x6d, 0x70, 0x6f, 0x72, 0x61, 0x6c, 0x69, 0x6f, 0x2e, 0x63, 0x61, 0x66, 0x65, 0x2e,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x4c, 0x69, 0x6e, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69,
	0x74, 0x65, 0x6d, 0x73, 0x22, 0x73, 0x0a, 0x1c, 0x4b, 0x69, 0x74, 0x63, 0x68, 0x65, 0x6e, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x04, 0x6c, 0x69, 0x6e, 0x65, 0x12, 0x3f, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x27, 0x2e, 0x74, 0x65, 0x6d, 0x70, 0x6f,
	0x72, 0x61, 0x6c, 0x69, 0x6f, 0x2e, 0x63, 0x61, 0x66, 0x65, 0x2e, 0x4b, 0x69, 0x74, 0x63, 0x68,
	0x65, 0x6e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x65, 0x0a, 0x12, 0x4b, 0x69, 0x74,
	0x63, 0x68, 0x65, 0x6e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x6f, 0x70, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x6f,
	0x70, 0x65, 0x6e, 0x12, 0x3b, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x25, 0x2e, 0x74, 0x65, 0x6d, 0x70, 0x6f, 0x72, 0x61, 0x6c, 0x69, 0x6f, 0x2e,
	0x63, 0x61, 0x66, 0x65, 0x2e, 0x4b, 0x69, 0x74, 0x63, 0x68, 0x65, 0x6e, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x4c, 0x69, 0x6e, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73,
	0x22, 0x14, 0x0a, 0x12, 0x4b, 0x69, 0x74, 0x63, 0x68, 0x65, 0x6e, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x6b, 0x0a, 0x14, 0x42, 0x61, 0x72, 0x69, 0x73, 0x74,
	0x61, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4c, 0x69, 0x6e, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x3f, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x27, 0x2e, 0x74, 0x65, 0x6d, 0x70, 0x6f, 0x72, 0x61, 0x6c, 0x69, 0x6f, 0x2e,
	0x63, 0x61, 0x66, 0x65, 0x2e, 0x42, 0x61, 0x72, 0x69, 0x73, 0x74, 0x61, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x49, 0x74, 0x65, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x22, 0x49, 0x0a, 0x11, 0x42, 0x61, 0x72, 0x69, 0x73, 0x74, 0x61, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x34, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x74, 0x65, 0x6d, 0x70, 0x6f, 0x72,
	0x61, 0x6c, 0x69, 0x6f, 0x2e, 0x63, 0x61, 0x66, 0x65, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4c,
	0x69, 0x6e, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x73,
	0x0a, 0x1c, 0x42, 0x61, 0x72, 0x69, 0x73, 0x74, 0x61, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x74,
	0x65, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x6c, 0x69, 0x6e, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x6c, 0x69,
	0x6e, 0x65, 0x12, 0x3f, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x27, 0x2e, 0x74, 0x65, 0x6d, 0x70, 0x6f, 0x72, 0x61, 0x6c, 0x69, 0x6f, 0x2e,
	0x63, 0x61, 0x66, 0x65, 0x2e, 0x42, 0x61, 0x72, 0x69, 0x73, 0x74, 0x61, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x49, 0x74, 0x65, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x22, 0x65, 0x0a, 0x12, 0x42, 0x61, 0x72, 0x69, 0x73, 0x74, 0x61, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6f, 0x70, 0x65,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x6f, 0x70, 0x65, 0x6e, 0x12, 0x3b, 0x0a,
	0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x74,
	0x65, 0x6d, 0x70, 0x6f, 0x72, 0x61, 0x6c, 0x69, 0x6f, 0x2e, 0x63, 0x61, 0x66, 0x65, 0x2e, 0x42,
	0x61, 0x72, 0x69, 0x73, 0x74, 0x61, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x4c, 0x69, 0x6e, 0x65, 0x49,
	0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x14, 0x0a, 0x12, 0x42, 0x61,
	0x72, 0x69, 0x73, 0x74, 0x61, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x22, 0x36, 0x0a, 0x1c, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x4c, 0x6f, 0x79, 0x61,
	0x6c, 0x74, 0x79, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x22, 0x35, 0x0a, 0x1b, 0x43, 0x75, 0x73, 0x74,
	0x6f, 0x6d, 0x65, 0x72, 0x4c, 0x6f, 0x79, 0x61, 0x6c, 0x74, 0x79, 0x50, 0x6f, 0x69, 0x6e, 0x74,
	0x73, 0x45, 0x61, 0x72, 0x6e, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x22,
	0x25, 0x0a, 0x0d, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49, 0x6e, 0x70, 0x75, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x22, 0x25, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e,
	0x74, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x75, 0x74, 0x68, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x75, 0x74, 0x68, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x2b, 0x0a,
	0x13, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x49,
	0x6e, 0x70, 0x75, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x4a, 0x0a, 0x14, 0x50, 0x72,
	0x6f, 0x63, 0x65, 0x73, 0x73, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x32, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x74, 0x65, 0x6d, 0x70, 0x6f, 0x72, 0x61, 0x6c, 0x69, 0x6f,
	0x2e, 0x63, 0x61, 0x66, 0x65, 0x2e, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x07, 0x70,
	0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x4f, 0x0a, 0x19, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73,
	0x73, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x66, 0x75, 0x6e, 0x64, 0x49, 0x6e,
	0x70, 0x75, 0x74, 0x12, 0x32, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x74, 0x65, 0x6d, 0x70, 0x6f, 0x72, 0x61, 0x6c, 0x69,
	0x6f, 0x2e, 0x63, 0x61, 0x66, 0x65, 0x2e, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x07,
	0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x1c, 0x0a, 0x1a, 0x50, 0x72, 0x6f, 0x63, 0x65,
	0x73, 0x73, 0x50, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x66, 0x75, 0x6e, 0x64, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x45, 0x0a, 0x15, 0x41, 0x64, 0x64, 0x4c, 0x6f, 0x79, 0x61,
	0x6c, 0x74, 0x79, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x22, 0x18, 0x0a, 0x16,
	0x41, 0x64, 0x64, 0x4c, 0x6f, 0x79, 0x61, 0x6c, 0x74, 0x79, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2a, 0x59, 0x0a, 0x0b, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x14, 0x50, 0x52, 0x4f, 0x44, 0x55, 0x43, 0x54,
	0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12,
	0x15, 0x0a, 0x11, 0x50, 0x52, 0x4f, 0x44, 0x55, 0x43, 0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f,
	0x46, 0x4f, 0x4f, 0x44, 0x10, 0x01, 0x12, 0x19, 0x0a, 0x15, 0x50, 0x52, 0x4f, 0x44, 0x55, 0x43,
	0x54, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x42, 0x45, 0x56, 0x45, 0x52, 0x41, 0x47, 0x45, 0x10,
	0x02, 0x2a, 0xb5, 0x01, 0x0a, 0x16, 0x4b, 0x69, 0x74, 0x63, 0x68, 0x65, 0x6e, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x25, 0x0a, 0x21,
	0x4b, 0x49, 0x54, 0x43, 0x48, 0x45, 0x4e, 0x5f, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f, 0x49, 0x54,
	0x45, 0x4d, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x50, 0x45, 0x4e, 0x44, 0x49, 0x4e,
	0x47, 0x10, 0x00, 0x12, 0x25, 0x0a, 0x21, 0x4b, 0x49, 0x54, 0x43, 0x48, 0x45, 0x4e, 0x5f, 0x4f,
	0x52, 0x44, 0x45, 0x52, 0x5f, 0x49, 0x54, 0x45, 0x4d, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53,
	0x5f, 0x53, 0x54, 0x41, 0x52, 0x54, 0x45, 0x44, 0x10, 0x01, 0x12, 0x27, 0x0a, 0x23, 0x4b, 0x49,
	0x54, 0x43, 0x48, 0x45, 0x4e, 0x5f, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f, 0x49, 0x54, 0x45, 0x4d,
	0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x43, 0x4f, 0x4d, 0x50, 0x4c, 0x45, 0x54, 0x45,
	0x44, 0x10, 0x02, 0x12, 0x24, 0x0a, 0x20, 0x4b, 0x49, 0x54, 0x43, 0x48, 0x45, 0x4e, 0x5f, 0x4f,
	0x52, 0x44, 0x45, 0x52, 0x5f, 0x49, 0x54, 0x45, 0x4d, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53,
	0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10, 0x03, 0x2a, 0xb5, 0x01, 0x0a, 0x16, 0x42, 0x61,
	0x72, 0x69, 0x73, 0x74, 0x61, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x25, 0x0a, 0x21, 0x42, 0x41, 0x52, 0x49, 0x53, 0x54, 0x41, 0x5f,
	0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f, 0x49, 0x54, 0x45, 0x4d, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55,
	0x53, 0x5f, 0x50, 0x45, 0x4e, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x00, 0x12, 0x25, 0x0a, 0x21, 0x42,
	0x41, 0x52, 0x49, 0x53, 0x54, 0x41, 0x5f, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f, 0x49, 0x54, 0x45,
	0x4d, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x53, 0x54, 0x41, 0x52, 0x54, 0x45, 0x44,
	0x10, 0x01, 0x12, 0x27, 0x0a, 0x23, 0x42, 0x41, 0x52, 0x49, 0x53, 0x54, 0x41, 0x5f, 0x4f, 0x52,
	0x44, 0x45, 0x52, 0x5f, 0x49, 0x54, 0x45, 0x4d, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f,
	0x43, 0x4f, 0x4d, 0x50, 0x4c, 0x45, 0x54, 0x45, 0x44, 0x10, 0x02, 0x12, 0x24, 0x0a, 0x20, 0x42,
	0x41, 0x52, 0x49, 0x53, 0x54, 0x41, 0x5f, 0x4f, 0x52, 0x44, 0x45, 0x52, 0x5f, 0x49, 0x54, 0x45,
	0x4d, 0x5f, 0x53, 0x54, 0x41, 0x54, 0x55, 0x53, 0x5f, 0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x10,
	0x03, 0x32, 0xcd, 0x07, 0x0a, 0x04, 0x43, 0x61, 0x66, 0x65, 0x12, 0x44, 0x0a, 0x05, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x12, 0x1b, 0x2e, 0x74, 0x65, 0x6d, 0x70, 0x6f, 0x72, 0x61, 0x6c, 0x69, 0x6f,
	0x2e, 0x63, 0x61, 0x66, 0x65, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x6e, 0x70, 0x75, 0x74,
	0x1a, 0x1c, 0x2e, 0x74, 0x65, 0x6d, 0x70, 0x6f, 0x72, 0x61, 0x6c, 0x69, 0x6f, 0x2e, 0x63, 0x61,
	0x66, 0x65, 0x2e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00,
	0x12, 0x50, 0x0a, 0x1c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x46, 0x75, 0x6c, 0x66, 0x69, 0x6c, 0x6d,
	0x65, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c,
	0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x22, 0x00, 0x12, 0x59, 0x0a, 0x0c, 0x4b, 0x69, 0x74, 0x63, 0x68, 0x65, 0x6e, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x12, 0x22, 0x2e, 0x74, 0x65, 0x6d, 0x70, 0x6f, 0x72, 0x61, 0x6c, 0x69, 0x6f, 0x2e,
	0x63, 0x61, 0x66, 0x65, 0x2e, 0x4b, 0x69, 0x74, 0x63, 0x68, 0x65, 0x6e, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x23, 0x2e, 0x74, 0x65, 0x6d, 0x70, 0x6f, 0x72, 0x61,
	0x6c, 0x69, 0x6f, 0x2e, 0x63, 0x61, 0x66, 0x65, 0x2e, 0x4b, 0x69, 0x74, 0x63, 0x68, 0x65, 0x6e,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x58, 0x0a,
	0x17, 0x4b, 0x69, 0x74, 0x63, 0x68, 0x65, 0x6e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x1a, 0x23, 0x2e, 0x74, 0x65, 0x6d, 0x70, 0x6f, 0x72, 0x61, 0x6c, 0x69, 0x6f, 0x2e, 0x63, 0x61,
	0x66, 0x65, 0x2e, 0x4b, 0x69, 0x74, 0x63, 0x68, 0x65, 0x6e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x00, 0x12, 0x67, 0x0a, 0x1c, 0x4b, 0x69, 0x74, 0x63, 0x68,
	0x65, 0x6e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x6c, 0x12, 0x2d, 0x2e, 0x74, 0x65, 0x6d, 0x70, 0x6f, 0x72,
	0x61, 0x6c, 0x69, 0x6f, 0x2e, 0x63, 0x61, 0x66, 0x65, 0x2e, 0x4b, 0x69, 0x74, 0x63, 0x68, 0x65,
	0x6e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00,
	0x12, 0x59, 0x0a, 0x0c, 0x42, 0x61, 0x72, 0x69, 0x73, 0x74, 0x61, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x12, 0x22, 0x2e, 0x74, 0x65, 0x6d, 0x70, 0x6f, 0x72, 0x61, 0x6c, 0x69, 0x6f, 0x2e, 0x63, 0x61,
	0x66, 0x65, 0x2e, 0x42, 0x61, 0x72, 0x69, 0x73, 0x74, 0x61, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49,
	0x6e, 0x70, 0x75, 0x74, 0x1a, 0x23, 0x2e, 0x74, 0x65, 0x6d, 0x70, 0x6f, 0x72, 0x61, 0x6c, 0x69,
	0x6f, 0x2e, 0x63, 0x61, 0x66, 0x65, 0x2e, 0x42, 0x61, 0x72, 0x69, 0x73, 0x74, 0x61, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x12, 0x58, 0x0a, 0x17, 0x42,
	0x61, 0x72, 0x69, 0x73, 0x74, 0x61, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x23,
	0x2e, 0x74, 0x65, 0x6d, 0x70, 0x6f, 0x72, 0x61, 0x6c, 0x69, 0x6f, 0x2e, 0x63, 0x61, 0x66, 0x65,
	0x2e, 0x42, 0x61, 0x72, 0x69, 0x73, 0x74, 0x61, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x22, 0x00, 0x12, 0x67, 0x0a, 0x1c, 0x42, 0x61, 0x72, 0x69, 0x73, 0x74, 0x61,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x53,
	0x69, 0x67, 0x6e, 0x61, 0x6c, 0x12, 0x2d, 0x2e, 0x74, 0x65, 0x6d, 0x70, 0x6f, 0x72, 0x61, 0x6c,
	0x69, 0x6f, 0x2e, 0x63, 0x61, 0x66, 0x65, 0x2e, 0x42, 0x61, 0x72, 0x69, 0x73, 0x74, 0x61, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x49, 0x74, 0x65, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x6b,
	0x0a, 0x21, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x4c, 0x6f, 0x79, 0x61, 0x6c, 0x74,
	0x79, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x45, 0x61, 0x72, 0x6e, 0x65, 0x64, 0x53, 0x69, 0x67,
	0x6e, 0x61, 0x6c, 0x12, 0x2c, 0x2e, 0x74, 0x65, 0x6d, 0x70, 0x6f, 0x72, 0x61, 0x6c, 0x69, 0x6f,
	0x2e, 0x63, 0x61, 0x66, 0x65, 0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x4c, 0x6f,
	0x79, 0x61, 0x6c, 0x74, 0x79, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x45, 0x61, 0x72, 0x6e, 0x65,
	0x64, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x83, 0x01, 0x0a, 0x21,
	0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x4c, 0x6f, 0x79, 0x61, 0x6c, 0x74, 0x79, 0x50,
	0x6f, 0x69, 0x6e, 0x74, 0x73, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x51, 0x75, 0x65, 0x72,
	0x79, 0x12, 0x2d, 0x2e, 0x74, 0x65, 0x6d, 0x70, 0x6f, 0x72, 0x61, 0x6c, 0x69, 0x6f, 0x2e, 0x63,
	0x61, 0x66, 0x65, 0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x4c, 0x6f, 0x79, 0x61,
	0x6c, 0x74, 0x79, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65,
	0x1a, 0x2d, 0x2e, 0x74, 0x65, 0x6d, 0x70, 0x6f, 0x72, 0x61, 0x6c, 0x69, 0x6f, 0x2e, 0x63, 0x61,
	0x66, 0x65, 0x2e, 0x43, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x4c, 0x6f, 0x79, 0x61, 0x6c,
	0x74, 0x79, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x22,
	0x00, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x74, 0x65, 0x6d, 0x70, 0x6f, 0x72, 0x61, 0x6c, 0x69, 0x6f, 0x2f, 0x74, 0x65, 0x6d, 0x70, 0x6f,
	0x72, 0x61, 0x6c, 0x2d, 0x63, 0x61, 0x66, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_cafe_proto_rawDescOnce sync.Once
	file_cafe_proto_rawDescData = file_cafe_proto_rawDesc
)

func file_cafe_proto_rawDescGZIP() []byte {
	file_cafe_proto_rawDescOnce.Do(func() {
		file_cafe_proto_rawDescData = protoimpl.X.CompressGZIP(file_cafe_proto_rawDescData)
	})
	return file_cafe_proto_rawDescData
}

var file_cafe_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_cafe_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_cafe_proto_goTypes = []interface{}{
	(ProductType)(0),                     // 0: temporalio.cafe.ProductType
	(KitchenOrderItemStatus)(0),          // 1: temporalio.cafe.KitchenOrderItemStatus
	(BaristaOrderItemStatus)(0),          // 2: temporalio.cafe.BaristaOrderItemStatus
	(*OrderLineItem)(nil),                // 3: temporalio.cafe.OrderLineItem
	(*OrderInput)(nil),                   // 4: temporalio.cafe.OrderInput
	(*OrderResult)(nil),                  // 5: temporalio.cafe.OrderResult
	(*KitchenOrderLineItem)(nil),         // 6: temporalio.cafe.KitchenOrderLineItem
	(*KitchenOrderInput)(nil),            // 7: temporalio.cafe.KitchenOrderInput
	(*KitchenOrderItemStatusUpdate)(nil), // 8: temporalio.cafe.KitchenOrderItemStatusUpdate
	(*KitchenOrderStatus)(nil),           // 9: temporalio.cafe.KitchenOrderStatus
	(*KitchenOrderResult)(nil),           // 10: temporalio.cafe.KitchenOrderResult
	(*BaristaOrderLineItem)(nil),         // 11: temporalio.cafe.BaristaOrderLineItem
	(*BaristaOrderInput)(nil),            // 12: temporalio.cafe.BaristaOrderInput
	(*BaristaOrderItemStatusUpdate)(nil), // 13: temporalio.cafe.BaristaOrderItemStatusUpdate
	(*BaristaOrderStatus)(nil),           // 14: temporalio.cafe.BaristaOrderStatus
	(*BaristaOrderResult)(nil),           // 15: temporalio.cafe.BaristaOrderResult
	(*CustomerLoyaltyPointsBalance)(nil), // 16: temporalio.cafe.CustomerLoyaltyPointsBalance
	(*CustomerLoyaltyPointsEarned)(nil),  // 17: temporalio.cafe.CustomerLoyaltyPointsEarned
	(*CustomerInput)(nil),                // 18: temporalio.cafe.CustomerInput
	(*Payment)(nil),                      // 19: temporalio.cafe.Payment
	(*ProcessPaymentInput)(nil),          // 20: temporalio.cafe.ProcessPaymentInput
	(*ProcessPaymentResult)(nil),         // 21: temporalio.cafe.ProcessPaymentResult
	(*ProcessPaymentRefundInput)(nil),    // 22: temporalio.cafe.ProcessPaymentRefundInput
	(*ProcessPaymentRefundResult)(nil),   // 23: temporalio.cafe.ProcessPaymentRefundResult
	(*AddLoyaltyPointsInput)(nil),        // 24: temporalio.cafe.AddLoyaltyPointsInput
	(*AddLoyaltyPointsResult)(nil),       // 25: temporalio.cafe.AddLoyaltyPointsResult
	(*emptypb.Empty)(nil),                // 26: google.protobuf.Empty
}
var file_cafe_proto_depIdxs = []int32{
	0,  // 0: temporalio.cafe.OrderLineItem.type:type_name -> temporalio.cafe.ProductType
	3,  // 1: temporalio.cafe.OrderInput.items:type_name -> temporalio.cafe.OrderLineItem
	1,  // 2: temporalio.cafe.KitchenOrderLineItem.status:type_name -> temporalio.cafe.KitchenOrderItemStatus
	3,  // 3: temporalio.cafe.KitchenOrderInput.items:type_name -> temporalio.cafe.OrderLineItem
	1,  // 4: temporalio.cafe.KitchenOrderItemStatusUpdate.status:type_name -> temporalio.cafe.KitchenOrderItemStatus
	6,  // 5: temporalio.cafe.KitchenOrderStatus.items:type_name -> temporalio.cafe.KitchenOrderLineItem
	2,  // 6: temporalio.cafe.BaristaOrderLineItem.status:type_name -> temporalio.cafe.BaristaOrderItemStatus
	3,  // 7: temporalio.cafe.BaristaOrderInput.items:type_name -> temporalio.cafe.OrderLineItem
	2,  // 8: temporalio.cafe.BaristaOrderItemStatusUpdate.status:type_name -> temporalio.cafe.BaristaOrderItemStatus
	11, // 9: temporalio.cafe.BaristaOrderStatus.items:type_name -> temporalio.cafe.BaristaOrderLineItem
	19, // 10: temporalio.cafe.ProcessPaymentResult.payment:type_name -> temporalio.cafe.Payment
	19, // 11: temporalio.cafe.ProcessPaymentRefundInput.payment:type_name -> temporalio.cafe.Payment
	4,  // 12: temporalio.cafe.Cafe.Order:input_type -> temporalio.cafe.OrderInput
	26, // 13: temporalio.cafe.Cafe.OrderFulfilmentStartedSignal:input_type -> google.protobuf.Empty
	7,  // 14: temporalio.cafe.Cafe.KitchenOrder:input_type -> temporalio.cafe.KitchenOrderInput
	26, // 15: temporalio.cafe.Cafe.KitchenOrderStatusQuery:input_type -> google.protobuf.Empty
	8,  // 16: temporalio.cafe.Cafe.KitchenOrderItemStatusSignal:input_type -> temporalio.cafe.KitchenOrderItemStatusUpdate
	12, // 17: temporalio.cafe.Cafe.BaristaOrder:input_type -> temporalio.cafe.BaristaOrderInput
	26, // 18: temporalio.cafe.Cafe.BaristaOrderStatusQuery:input_type -> google.protobuf.Empty
	13, // 19: temporalio.cafe.Cafe.BaristaOrderItemStatusSignal:input_type -> temporalio.cafe.BaristaOrderItemStatusUpdate
	17, // 20: temporalio.cafe.Cafe.CustomerLoyaltyPointsEarnedSignal:input_type -> temporalio.cafe.CustomerLoyaltyPointsEarned
	16, // 21: temporalio.cafe.Cafe.CustomerLoyaltyPointsBalanceQuery:input_type -> temporalio.cafe.CustomerLoyaltyPointsBalance
	5,  // 22: temporalio.cafe.Cafe.Order:output_type -> temporalio.cafe.OrderResult
	26, // 23: temporalio.cafe.Cafe.OrderFulfilmentStartedSignal:output_type -> google.protobuf.Empty
	10, // 24: temporalio.cafe.Cafe.KitchenOrder:output_type -> temporalio.cafe.KitchenOrderResult
	9,  // 25: temporalio.cafe.Cafe.KitchenOrderStatusQuery:output_type -> temporalio.cafe.KitchenOrderStatus
	26, // 26: temporalio.cafe.Cafe.KitchenOrderItemStatusSignal:output_type -> google.protobuf.Empty
	15, // 27: temporalio.cafe.Cafe.BaristaOrder:output_type -> temporalio.cafe.BaristaOrderResult
	14, // 28: temporalio.cafe.Cafe.BaristaOrderStatusQuery:output_type -> temporalio.cafe.BaristaOrderStatus
	26, // 29: temporalio.cafe.Cafe.BaristaOrderItemStatusSignal:output_type -> google.protobuf.Empty
	26, // 30: temporalio.cafe.Cafe.CustomerLoyaltyPointsEarnedSignal:output_type -> google.protobuf.Empty
	16, // 31: temporalio.cafe.Cafe.CustomerLoyaltyPointsBalanceQuery:output_type -> temporalio.cafe.CustomerLoyaltyPointsBalance
	22, // [22:32] is the sub-list for method output_type
	12, // [12:22] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_cafe_proto_init() }
func file_cafe_proto_init() {
	if File_cafe_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_cafe_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderLineItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cafe_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cafe_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cafe_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KitchenOrderLineItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cafe_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KitchenOrderInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cafe_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KitchenOrderItemStatusUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cafe_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KitchenOrderStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cafe_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KitchenOrderResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cafe_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BaristaOrderLineItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cafe_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BaristaOrderInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cafe_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BaristaOrderItemStatusUpdate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cafe_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BaristaOrderStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cafe_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BaristaOrderResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cafe_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomerLoyaltyPointsBalance); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cafe_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomerLoyaltyPointsEarned); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cafe_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CustomerInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cafe_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Payment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cafe_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessPaymentInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cafe_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessPaymentResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cafe_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessPaymentRefundInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cafe_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcessPaymentRefundResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cafe_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddLoyaltyPointsInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_cafe_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddLoyaltyPointsResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_cafe_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_cafe_proto_goTypes,
		DependencyIndexes: file_cafe_proto_depIdxs,
		EnumInfos:         file_cafe_proto_enumTypes,
		MessageInfos:      file_cafe_proto_msgTypes,
	}.Build()
	File_cafe_proto = out.File
	file_cafe_proto_rawDesc = nil
	file_cafe_proto_goTypes = nil
	file_cafe_proto_depIdxs = nil
}
